### ISSUE TITLE
Update for OCP4

### ISSUE THREAD

**Issue by mueroema** [openshift/request-header-saml-service-provider#38]
Hello,
it would be helpful to get this document updated for Openshift 4. Thank you.

**Comment by andresmmujica** [comment]
have any one tested in OS4.x ?  I'm currently exploring this.

**Comment by briantward** [comment]
This project requires pretty much a complete rebuild for OpenShift 4.  I would recommend you look at using something like Keycloak or RH-SSO to bridge your SAML based communication over to Oauth.  Most modern Identity Providers offer both protocols now, and easily bridge between the two.  This Request Header SAML Service Provider solution is not much more than a SAML SP auth server that bridges authentication directly over to the Oauth server inside OpenShift.  The intention was to build an operator that deploys all this for OpenShift 4, but since there is already easy configuration in Keycloak, we have not seen a large demand here.
